#Connecting pod  to replicaset
#apiVersion: apps/v1
#kind: ReplicaSet
#metadata:
#spec:
#  replicas:
#  selector:
#     matchLables:
#        pod: label
#  template:
#    copy pod definition from metadata

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: gcr.io/google-containers/busybox
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
