# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
  namespace: default
  labels:
    app: myapp-pvc
spec:
  storageClassName: myapp-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
